---
version: "3"

volumes:
  config:

services:
  renderer:
    image: giof71/gmrender-resurrect:latest
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - FRIENDLY_NAME=${FRIENDLY_NAME:-gmrender}
      - GSTOUT_AUDIOPIPE=audioresample ! audio/x-raw, rate=44100, format=S16LE ! filesink location=/fifo/fifo
    volumes:
      - config:/config
      - /run/user/${PUID:-1000}/pulse:/run/user/${PUID:-1000}/pulse
    restart: unless-stopped
