---
version: "3"

volumes:
  config:

services:
  renderer:
    image: giof71/gmrender-resurrect:latest
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - AUDIO_GID=${AUDIO_GID:-29}
      - CARD_NAME=${CARD_NAME:-}
      - CARD_INDEX=${CARD_INDEX:-}
      - FRIENDLY_NAME=${FRIENDLY_NAME:-gmrender}
      - GSTOUT_INITIAL_VOLUME_DB=${GSTOUT_INITIAL_VOLUME_DB:-}
    volumes:
      - config:/config
    restart: unless-stopped
