---
version: "3"

volumes:
  config:

services:
  renderer:
    image: giof71/gmrender-resurrect:latest
    network_mode: host
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - FRIENDLY_NAME=${FRIENDLY_NAME:-gmrender}
      - GSTOUT_INITIAL_VOLUME_DB=${GSTOUT_INITIAL_VOLUME_DB:-}
      - GSTOUT_AUDIOPIPE=audioresample ! audio/x-raw, rate=44100, format=S16LE ! filesink location=/fifo/fifo
    volumes:
      - config:/config
      - ./fifo:/fifo
    restart: unless-stopped
