---
version: "3"

volumes:
  config:

services:
  renderer:
    image: giof71/gmrender-resurrect:latest
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - FRIENDLY_NAME=${FRIENDLY_NAME:-gmrender pulse}
      - GSTOUT_INITIAL_VOLUME_DB=${GSTOUT_INITIAL_VOLUME_DB:-}
    volumes:
      - config:/config
      - ./fifo:/fifo
    restart: unless-stopped
